version: "3"
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  publy_db:
    image: postgres:14.1-alpine
    command:
      - postgres
      - -c
      - log_statement=all
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=1
      - -c
      - max_replication_slots=1
    container_name: publy_db
    ports:
      - "17432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpw
      - POSTGRES_USER=klaus
      - POSTGRES_DB=publy_db
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/db-data:/var/lib/postgresql/data
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
    links:
      - kafka
      - publy_db
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses